
//
//  Copyright (C) 2009 - Bernd H Stramm
//


// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "satview.h"
/** @brief This is generated from FLUID, for the most part.
*/
#include "version.h"
using namespace berndsutil;
#include "berndsutil.h"

DisplayControl::DisplayControl() {
  { Selection = new Fl_Double_Window(345, 400, "Satview Control");
    Selection->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(5, 115, 335, 85);
      o->box(FL_THIN_UP_BOX);
      o->color((Fl_Color)147);
      { DitchDB = new Fl_Button(20, 155, 65, 40, "Clear Data");
        DitchDB->color(FL_RED);
        DitchDB->selection_color((Fl_Color)208);
        DitchDB->callback((Fl_Callback*)DitchDB_cb);
        DitchDB->align(FL_ALIGN_WRAP);
      } // Fl_Button* DitchDB
      { ReloadDB = new Fl_Button(195, 155, 65, 40, "Reload Data");
        ReloadDB->box(FL_THIN_UP_BOX);
        ReloadDB->color(FL_LIGHT1);
        ReloadDB->callback((Fl_Callback*)ReloadDB_cb);
        ReloadDB->align(FL_ALIGN_WRAP);
      } // Fl_Button* ReloadDB
      { ConnectDB = new Fl_Button(105, 165, 70, 30, "Connect");
        ConnectDB->box(FL_THIN_UP_BOX);
        ConnectDB->callback((Fl_Callback*)ConnectDB_cb);
      } // Fl_Button* ConnectDB
      { ServerName = new Fl_Input(30, 120, 230, 25, "Server");
        ServerName->color((Fl_Color)70);
        ServerName->callback((Fl_Callback*)ServerName_cb);
        ServerName->align(FL_ALIGN_BOTTOM);
        ServerName->when(FL_WHEN_CHANGED);
      } // Fl_Input* ServerName
      { WebCheck = new Fl_Round_Button(265, 130, 75, 15, "Web");
        WebCheck->down_box(FL_ROUND_DOWN_BOX);
        WebCheck->callback((Fl_Callback*)WebCheck_cb, (void*)(DirectCheck));
      } // Fl_Round_Button* WebCheck
      { DirectCheck = new Fl_Round_Button(265, 150, 25, 25, "Direct");
        DirectCheck->down_box(FL_ROUND_DOWN_BOX);
        DirectCheck->callback((Fl_Callback*)DirectCheck_cb, (void*)(WebCheck));
      } // Fl_Round_Button* DirectCheck
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(5, 5, 335, 110);
      o->box(FL_THIN_UP_BOX);
      { Filename = new Fl_Input(75, 15, 195, 25, "Image ");
        Filename->callback((Fl_Callback*)Filename_cb);
      } // Fl_Input* Filename
      { ChangeImage = new Fl_Button(275, 5, 60, 35, "Load New");
        ChangeImage->labelsize(10);
        ChangeImage->callback((Fl_Callback*)ChangeImage_cb);
        ChangeImage->align(FL_ALIGN_WRAP);
      } // Fl_Button* ChangeImage
      { ChangeDate = new Fl_Input(75, 80, 195, 25, "Date ");
        ChangeDate->callback((Fl_Callback*)ChangeDate_cb);
      } // Fl_Input* ChangeDate
      { Seconds = new Fl_Input(75, 50, 195, 25, "Seconds ");
      } // Fl_Input* Seconds
      o->end();
    } // Fl_Group* o
    { Quit = new Fl_Button(285, 50, 45, 45, "Quit");
      Quit->box(FL_PLASTIC_UP_BOX);
      Quit->down_box(FL_PLASTIC_DOWN_BOX);
      Quit->color((Fl_Color)4);
      Quit->selection_color((Fl_Color)1);
      Quit->callback((Fl_Callback*)Quit_cb);
    } // Fl_Button* Quit
    { Fl_Group* o = new Fl_Group(175, 210, 75, 180, "Run Forward");
      o->box(FL_THIN_UP_BOX);
      o->align(129|FL_ALIGN_INSIDE);
      { RunForward = new Fl_Button(180, 250, 60, 25, "All");
        RunForward->callback((Fl_Callback*)RunForward_cb);
      } // Fl_Button* RunForward
      { Run6 = new Fl_Button(180, 330, 60, 20, "6 hours");
        Run6->callback((Fl_Callback*)RunForTo_cb, (void*)(new Store<int>(6*60*60)));
      } // Fl_Button* Run6
      { RunDay = new Fl_Button(180, 305, 60, 25, "1 day");
        RunDay->callback((Fl_Callback*)RunForTo_cb, (void*)(new Store<int>(24*60*60)));
      } // Fl_Button* RunDay
      { RunWeek = new Fl_Button(180, 280, 60, 25, "1 week");
        RunWeek->callback((Fl_Callback*)RunForTo_cb, (void*)(new Store<int>(7*24*60*60)));
      } // Fl_Button* RunWeek
      { StepFore = new Fl_Button(180, 355, 60, 25, "Step");
        StepFore->callback((Fl_Callback*)Step_cb, (void*)(new Store<int>(1)));
      } // Fl_Button* StepFore
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(90, 210, 75, 180, "Run   Back");
      o->box(FL_THIN_UP_BOX);
      o->align(129|FL_ALIGN_INSIDE);
      { RunBackAll = new Fl_Button(95, 250, 60, 25, "All");
        RunBackAll->callback((Fl_Callback*)RunBack_cb);
      } // Fl_Button* RunBackAll
      { RunBack6 = new Fl_Button(95, 330, 60, 20, "6 hours");
        RunBack6->callback((Fl_Callback*)RunBackTo_cb, (void*)(new Store<int>(-6*60*60)));
      } // Fl_Button* RunBack6
      { RunBackDay = new Fl_Button(95, 305, 60, 25, "1 day");
        RunBackDay->callback((Fl_Callback*)RunBackTo_cb, (void*)(new Store<int>(-24*60*60)));
      } // Fl_Button* RunBackDay
      { RunBackWeek = new Fl_Button(95, 280, 60, 25, "1 week");
        RunBackWeek->callback((Fl_Callback*)RunBackTo_cb, (void*)(new Store<int>(-7*24*60*60)));
      } // Fl_Button* RunBackWeek
      { StepBack = new Fl_Button(95, 355, 60, 25, "Step");
        StepBack->callback((Fl_Callback*)Step_cb, (void*)(new Store<int>(-1)));
      } // Fl_Button* StepBack
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(5, 220, 70, 150, "Rewind");
      o->box(FL_THIN_UP_BOX);
      o->align(129|FL_ALIGN_INSIDE);
      { RewindAll = new Fl_Button(10, 260, 60, 25, "All");
        RewindAll->callback((Fl_Callback*)RewindAll_cb);
      } // Fl_Button* RewindAll
      { Rewind6 = new Fl_Button(10, 340, 60, 20, "6 hours");
        Rewind6->callback((Fl_Callback*)RewindTo_cb, (void*)(new Store<int>(-6*60*60)));
      } // Fl_Button* Rewind6
      { RewindDay = new Fl_Button(10, 315, 60, 25, "1 day");
        RewindDay->callback((Fl_Callback*)RewindTo_cb, (void*)(new Store<int>(-24*60*60)));
      } // Fl_Button* RewindDay
      { RewindWeek = new Fl_Button(10, 290, 60, 25, "1 week");
        RewindWeek->callback((Fl_Callback*)RewindTo_cb, (void*)(new Store<int>(-7*24*60*60)));
      } // Fl_Button* RewindWeek
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(265, 220, 70, 150, "Advance");
      o->box(FL_THIN_UP_BOX);
      o->align(129|FL_ALIGN_INSIDE);
      { WindAll = new Fl_Button(270, 260, 60, 25, "All");
        WindAll->callback((Fl_Callback*)WindAll_cb);
      } // Fl_Button* WindAll
      { Wind6 = new Fl_Button(270, 340, 60, 20, "6 hours");
        Wind6->callback((Fl_Callback*)WindForeTo_cb, (void*)(new Store<int>(6*60*60)));
      } // Fl_Button* Wind6
      { WIndDay = new Fl_Button(270, 315, 60, 25, "1 day");
        WIndDay->callback((Fl_Callback*)WindForeTo_cb, (void*)(new Store<int>(24*60*60)));
      } // Fl_Button* WIndDay
      { WindWeek = new Fl_Button(270, 290, 60, 25, "1 week");
        WindWeek->callback((Fl_Callback*)WindForeTo_cb, (void*)(new Store<int>(7*24*60*60)));
      } // Fl_Button* WindWeek
      o->end();
    } // Fl_Group* o
    Selection->end();
    Selection->resizable(Selection);
  } // Fl_Double_Window* Selection
  { ImageWin = new Fl_Double_Window(700, 580, "Satview Image");
    ImageWin->user_data((void*)(this));
    { PicBox = new Fl_Box(5, 3, 685, 571);
      Fl_Group::current()->resizable(PicBox);
    } // Fl_Box* PicBox
    ImageWin->end();
  } // Fl_Double_Window* ImageWin
}
